# Generated by Django 3.0.7 on 2020-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200615_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='deskripso produk', max_length=1000),
        ),
    ]
