# Generated by Django 3.0.7 on 2020-06-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
    ]
