# Generated by Django 3.0.7 on 2020-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200617_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='deskripso produk'),
        ),
    ]
