# Generated by Django 3.0.7 on 2020-07-09 09:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200709_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=product.models.product_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='live_preview',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
