# Generated by Django 3.0.7 on 2020-07-10 00:54

from django.db import migrations, models
import django.db.models.deletion
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0004_auto_20200702_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover', models.ImageField(null=True, upload_to=sample.models.sample_directory_path)),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Technology')),
            ],
        ),
    ]
