# Generated by Django 3.0.7 on 2020-06-15 10:21

from django.db import migrations, models
import user_area.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user_area.models.user_directory_path),
        ),
    ]
