# Generated by Django 3.0.7 on 2020-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loyal_point',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10),
        ),
    ]
