# Generated by Django 3.0.7 on 2020-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
