# Generated by Django 3.0.7 on 2020-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='initialPrice',
            new_name='initial_price',
        ),
    ]
