# Generated by Django 3.0.7 on 2020-07-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0004_auto_20200702_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Technology')),
            ],
        ),
    ]
