# Generated by Django 3.0.7 on 2020-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200619_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
