# Generated by Django 3.0.7 on 2020-06-19 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20200619_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 7, 0, 2, 728593, tzinfo=utc)),
        ),
    ]
