# Generated by Django 3.0.7 on 2020-06-19 07:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20200619_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceporductitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='invoice.InvoiceProduct'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 7, 34, 6, 23614, tzinfo=utc)),
        ),
    ]
