# Generated by Django 3.0.7 on 2020-06-19 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200617_1443'),
        ('invoice', '0007_auto_20200619_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceporductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_invoice', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 7, 36, 59, 364455, tzinfo=utc)),
        ),
    ]
