# Generated by Django 3.0.7 on 2020-06-19 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20200619_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceporductitem',
            name='count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 9, 55, 50, 892391, tzinfo=utc)),
        ),
    ]
