# Generated by Django 3.0.7 on 2020-06-21 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20200621_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceporductitem',
            old_name='count',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='productbasket',
            old_name='count',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 14, 47, 40, 506218, tzinfo=utc)),
        ),
    ]
