# Generated by Django 3.0.7 on 2020-06-21 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20200621_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 15, 9, 12, 233866, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_from', models.CharField(max_length=50)),
                ('name_from', models.CharField(max_length=100)),
                ('payment_from', models.CharField(max_length=50)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.PaymentMethod')),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.PaymentAccount')),
            ],
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.PaymentConfirmation'),
        ),
    ]
