# Generated by Django 3.0.7 on 2020-06-21 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20200621_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 15, 21, 22, 653059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
