# Generated by Django 3.0.7 on 2020-06-22 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20200621_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 9, 29, 10, 726121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.PaymentConfirmation'),
        ),
    ]
