# Generated by Django 3.0.7 on 2020-06-26 01:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_auto_20200622_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 1, 52, 7, 573418, tzinfo=utc)),
        ),
    ]
