# Generated by Django 3.0.7 on 2020-06-26 02:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200617_1443'),
        ('invoice', '0017_auto_20200626_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='item',
            field=models.ManyToManyField(through='invoice.InvoicePorductItem', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='invoiceporductitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.InvoiceProduct'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 2, 0, 42, 921581, tzinfo=utc)),
        ),
    ]
