# Generated by Django 3.0.7 on 2020-06-26 02:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200617_1443'),
        ('invoice', '0019_auto_20200626_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoicePorductItem',
            new_name='InvoiceProductItem',
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 2, 15, 1, 510430, tzinfo=utc)),
        ),
    ]
