# Generated by Django 3.0.7 on 2020-06-26 02:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20200626_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 2, 22, 50, 771921, tzinfo=utc)),
        ),
    ]
