# Generated by Django 3.0.7 on 2020-06-26 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_auto_20200626_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproductitem',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 9, 10, 47, 320968, tzinfo=utc)),
        ),
    ]
