# Generated by Django 3.0.7 on 2020-06-30 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_auto_20200628_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 6, 33, 59, 39027, tzinfo=utc)),
        ),
    ]
