# Generated by Django 3.0.7 on 2020-07-02 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_auto_20200702_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 11, 57, 22, 91653, tzinfo=utc)),
        ),
    ]
