# Generated by Django 3.0.7 on 2020-07-02 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_auto_20200702_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 15, 52, 24, 52226, tzinfo=utc)),
        ),
    ]
