# Generated by Django 3.0.7 on 2020-07-08 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_auto_20200702_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 6, 24, 58, 14508, tzinfo=utc)),
        ),
    ]
