# Generated by Django 3.0.7 on 2020-07-08 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_auto_20200708_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 8, 11, 50, 428437, tzinfo=utc)),
        ),
    ]
