# Generated by Django 3.0.7 on 2020-07-09 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_auto_20200708_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 46, 20, 39619, tzinfo=utc)),
        ),
    ]
