# Generated by Django 3.0.7 on 2020-07-09 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0034_auto_20200709_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 9, 36, 50, 53912, tzinfo=utc)),
        ),
    ]
