# Generated by Django 3.0.7 on 2020-07-10 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_auto_20200709_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 0, 54, 58, 813480, tzinfo=utc)),
        ),
    ]
