# Generated by Django 3.0.7 on 2020-07-10 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_auto_20200710_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 12, 2, 18, 48, 612196, tzinfo=utc)),
        ),
    ]
